### ISSUE TITLE
Why is ...

### ISSUE THREAD

**Issue by AaronGulman** [itsYoungeun/MERN-Stack#1] opened 2024-11-04 21:50 UTC
Hi ,
I apologize for asking but is there any reason in particular as to why you committed you `.env `? It is just that it is not really recommended and it is a  good practice to avoid doing that completely even when you are doing something lightweight and insignificant. However, now that I have access to your mongodb key this could result in data theft, data manipulation, or even complete data loss if I were to do perform anything malicious. 

Think about it this way : you are working on some project and added some data even dummy data and then you have someone like me who connects to your DB and erases everything , I bet you wouldn't be very happy if that were to happen !

Though I am pretty sure you already knew all this and probably simply thought it wasn't important enough + if you use VScode and forgot to add your `.env ` to `.gitignore ` ,it is possible that you just staged all changed files and committed them all at once.

But hey , you're doing great and good luck everything , I have more 1 issue that I want to mention though !

**Comment by itsYoungeun** [comment] 2024-11-04 23:30
Dear sir,
I did not realize and am at your mercy  I thought I deleted the node modules file and added .env to the gitignore file but somehow the files got committed regardless.  I'm not sure what the problem is but I will look into trying to fix this. Thank you for all your pointers and direction, I am very grateful. 

    On Monday, November 4, 2024 at 06:50:34 PM GMT-3, AaronGulman ***@***.***> wrote:  
 
 


Hi ,
I apologize for asking but is there any reason in particular as to why you committed you .env ? It is just that it is not really recommended and it is a good practice to avoid doing that completely even when you are doing something lightweight and insignificant. However, now that I have access to your mongodb key this could result in data theft, data manipulation, or even complete data loss if I were to do perform anything malicious.

Think about it this way : you are working on some project and added some data even dummy data and then you have someone like me who connects to your DB and erases everything , I bet you wouldn't be very happy if that were to happen !

Though I am pretty sure you already knew all this and probably simply thought it wasn't important enough + if you use VScode and forgot to add your .env  to .gitignore  ,it is possible that you just staged all changed files and committed them all at once.

But hey , you're doing great and good luck everything , I have more 1 issue that I want to mention though !

**Comment by AaronGulman** [comment] 2024-11-05 02:00
Hi !! 

It's alright ,everything is amazing , it's just a tiny thing ,don't worry about it !!😱 

> Dear sir, I did not realize and am at your mercy  I thought I deleted the node modules file and added .env to the gitignore file but somehow the files got committed regardless.  I'm not sure what the problem is but I will look into trying to fix this. Thank you for all your pointers and direction, I am very grateful.  On Monday, November 4, 2024 at 06:50:34 PM GMT-3, AaronGulman ***@***.***> wrote: Hi , I apologize for asking but is there any reason in particular as to why you committed you .env ? It is just that it is not really recommended and it is a good practice to avoid doing that completely even when you are doing something lightweight and insignificant. However, now that I have access to your mongodb key this could result in data theft, data manipulation, or even complete data loss if I were to do perform anything malicious. Think about it this way : you are working on some project and added some data even dummy data and then you have someone like me who connects to your DB and erases everything , I bet you wouldn't be very happy if that were to happen ! Though I am pretty sure you already knew all this and probably simply thought it wasn't important enough + if you use VScode and forgot to add your .env to .gitignore ,it is possible that you just staged all changed files and committed them all at once. But hey , you're doing great and good luck everything , I have more 1 issue that I want to mention though ! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Closed as completed** 2024-11-05 15:44 UTC
